package com.bloomtechlabs.coderheroesbea.entities;

import javax.persistence.*;

@Entity
@Table(name = "parents")
public class Parents {
    private int parent_id;
    private Profiles profile;

    /**
     * Constructor.
     * Default constructor is required to have Hibernate initialize the entity.
     */
    public Parents() {

    }

    /**
     * Constructor with parent_id.
     * @param parent_id - primary key, auto-increments, generated by database
     */
    public Parents(int parent_id) {
        this.parent_id = parent_id;
    }

    /**
     * Constructor with all fields.
     * @param parent_id - primary key, auto-increments, generated by database
     * @param profile   - required, foreign key
     */
    public Parents(int parent_id, Profiles profile) {
        this.parent_id = parent_id;
        this.profile = profile;
    }

    @Id
    @Column(name = "parent_id")
    public int getParent_id() {
        return parent_id;
    }

    public void setParent_id(int parent_id) {
        this.parent_id = parent_id;
    }

    @OneToOne(cascade = CascadeType.REMOVE)
    @JoinColumn(name = "profile_id", referencedColumnName = "profile_id", nullable = false, unique = true)
    public Profiles getProfile() {
        return profile;
    }

    public void setProfile(Profiles profile) {
        this.profile = profile;
    }
}
