package com.bloomtechlabs.coderheroesbea.entities;

import javax.persistence.*;

@Entity
@Table(name = "student_badges")
public class StudentBadges {
    private int student_badge_id;
    private Children children;
    private FeedbackBadges feedbackBadges;

    /**
     * Constructor.
     * Default constructor is required to have Hibernate initialize the entity.
     */
    public StudentBadges() {

    }

    /**
     * Constructor with student_badge_id.
     * @param student_badge_id - primary key, auto-increments, generated by database
     */
    public StudentBadges(int student_badge_id) {
        this.student_badge_id = student_badge_id;
    }

    /**
     * Constructor with all fields.
     * @param student_badge_id - primary key, auto-increments, generated by database
     * @param children         - required, foreign key
     * @param feedbackBadges   - required, foreign key
     */
    public StudentBadges(int student_badge_id, Children children, FeedbackBadges feedbackBadges) {
        this.student_badge_id = student_badge_id;
        this.children = children;
        this.feedbackBadges = feedbackBadges;
    }

    @Id
    @Column(name = "student_badge_id")
    public int getStudent_badge_id() {
        return student_badge_id;
    }

    public void setStudent_badge_id(int student_badge_id) {
        this.student_badge_id = student_badge_id;
    }

    @OneToOne(cascade = CascadeType.REMOVE)
    @JoinColumn(name = "child_id", referencedColumnName = "child_id", nullable = false)
    public Children getChildren() {
        return children;
    }

    public void setChildren(Children children) {
        this.children = children;
    }

    @OneToOne(cascade = CascadeType.REMOVE)
    @JoinColumn(name = "badge_id", referencedColumnName = "badge_id", nullable = false)
    public FeedbackBadges getFeedbackBadges() {
        return feedbackBadges;
    }

    public void setFeedbackBadges(FeedbackBadges feedbackBadges) {
        this.feedbackBadges = feedbackBadges;
    }
}
